server:
  port: ${USER_SERVICE_PORT}

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://${DB_HOSTNAME}:3306/journal?createDatabaseIfNotExist=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    show-sql: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

