name: google-java-format

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
    - name: Google Java Format
      uses: axel-op/googlejavaformat-action@v3
      with:
          args: "--set-exit-if-changed"
