name: Link Jira
on:
  pull_request:
    types: [ opened ]
    branches: [ "develop" ]

env:
  PR_NUMBER: ${{ github.event.number }}
  BRANCH_NAME: ${{ github.head_ref }}
  BASE_NAME: ${{ github.base_ref }}

jobs:
  update_pr:
    name: Update PR Description
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Add Jira link
        run: |
          ISSUE_NUMBER=$(echo $BRANCH_NAME | grep -oP 'ANYDAY-\K\d+')
          CURRENT_BODY=$(gh pr view $PR_NUMBER --json body -q .body)
          JIRA_LINK=$(echo -e "- [Jira](https://hyoungjoojin.atlassian.net/browse/ANYDAY-$ISSUE_NUMBER)")
          NEW_BODY=$(echo -e "${CURRENT_BODY}\n\n${JIRA_LINK}\n\n")
          gh pr edit $PR_NUMBER --body $NEW_BODY
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
